version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cjDB
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cjDB
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cj-network

volumes:
  postgres-data:

networks:
  cj-network:
    driver: bridge